version: '3.9'

services:
  api:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - ./backend/app:/app/app

  web:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=1
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      api:
        condition: service_healthy